# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MusicPlayerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import threading
import time
import sys


class Ui_GesturePlayer(object):
    def setupUi(self, GesturePlayer):
        ##各種GUI的設定
        GesturePlayer.setObjectName("GesturePlayer")
        GesturePlayer.resize(591, 332)
        self.centralwidget = QtWidgets.QWidget(GesturePlayer)
        self.centralwidget.setObjectName("centralwidget")
        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setGeometry(QtCore.QRect(30, 230, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Eras Demi ITC")
        font.setPointSize(48)
        self.prevButton.setFont(font)
        self.prevButton.setObjectName("prevButton")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(390, 230, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Eras Demi ITC")
        font.setPointSize(48)
        self.nextButton.setFont(font)
        self.nextButton.setCheckable(False)
        self.nextButton.setObjectName("nextButton")
        self.pauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.pauseButton.setGeometry(QtCore.QRect(220, 270, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(20)
        self.pauseButton.setFont(font)
        self.pauseButton.setObjectName("pauseButton")
        self.songName = QtWidgets.QLabel(self.centralwidget)
        self.songName.setGeometry(QtCore.QRect(120, 150, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight Condensed")
        font.setPointSize(20)
        self.songName.setFont(font)
        self.songName.setAlignment(QtCore.Qt.AlignCenter)
        self.songName.setObjectName("songName")
        self.className = QtWidgets.QLabel(self.centralwidget)
        self.className.setGeometry(QtCore.QRect(190, 70, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(14)
        self.className.setFont(font)
        self.className.setAlignment(QtCore.Qt.AlignCenter)
        self.className.setObjectName("className")
        self.styleButton = QtWidgets.QPushButton(self.centralwidget)
        self.styleButton.setGeometry(QtCore.QRect(220, 230, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Eras Demi ITC")
        font.setPointSize(16)
        self.styleButton.setFont(font)
        self.styleButton.setObjectName("styleButton")
        self.gestureUse = QtWidgets.QCheckBox(self.centralwidget)
        self.gestureUse.setGeometry(QtCore.QRect(20, 60, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.gestureUse.setFont(font)
        self.gestureUse.setObjectName("gestureUse")
        self.showCameraUse = QtWidgets.QCheckBox(self.centralwidget)
        self.showCameraUse.setGeometry(QtCore.QRect(20, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.showCameraUse.setFont(font)
        self.showCameraUse.setObjectName("showCameraUse")
        self.cameraNum = QtWidgets.QLineEdit(self.centralwidget)
        self.cameraNum.setGeometry(QtCore.QRect(170, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.cameraNum.setFont(font)
        self.cameraNum.setObjectName("cameraNum")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        GesturePlayer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GesturePlayer)
        self.statusbar.setObjectName("statusbar")
        GesturePlayer.setStatusBar(self.statusbar)
        ##各種GUI的設定
        self.retranslateUi(GesturePlayer)
        QtCore.QMetaObject.connectSlotsByName(GesturePlayer)

        #限制Camera Numer的輸入
        regex = QtCore.QRegExp("[0-9]")
        validator = QtGui.QRegExpValidator(regex,self.cameraNum)
        self.cameraNum.setValidator(validator)

        self.showCameraUse.setEnabled(False) #未啟用手勢操作，不能顯示camera
        self.__setEventListener()

        self.isGesThreadRun=False #手勢辨識執行續的開關
        self.__PlayerSetting() #設置Music Player

    def retranslateUi(self, GesturePlayer):
        ##GUI的設定
        _translate = QtCore.QCoreApplication.translate
        GesturePlayer.setWindowTitle(_translate("GesturePlayer", "MainWindow"))
        self.prevButton.setText(_translate("GesturePlayer", "Prev"))
        self.nextButton.setText(_translate("GesturePlayer", "Next"))
        self.pauseButton.setText(_translate("GesturePlayer", "Play"))
        self.songName.setText(_translate("GesturePlayer", "Blue00.mp3"))
        self.className.setText(_translate("GesturePlayer", "Blue"))
        self.styleButton.setText(_translate("GesturePlayer", "Style Change"))
        self.gestureUse.setText(_translate("GesturePlayer", "Gesture"))
        self.showCameraUse.setText(_translate("GesturePlayer", "Show Camera"))
        self.cameraNum.setText(_translate("GesturePlayer", "0"))
        self.label.setText(_translate("GesturePlayer", "Camera Number:"))

    def __setEventListener(self): #設定按鈕的event listener
        self.nextButton.clicked.connect(self.__nextPress)
        self.prevButton.clicked.connect(self.__prevPress)
        self.pauseButton.clicked.connect(self.__pausePress)
        self.styleButton.clicked.connect(self.__stylePress)
        self.gestureUse.clicked.connect(self.__gesturePress)
        self.cameraNum.textChanged.connect(self.__camCheck)
    
    def __PlayerSetting(): #設置Music Player
        pass

    def __camCheck(self):
        cam_num = self.cameraNum.text()
        if cam_num=="":
            self.gestureUse.setEnabled(False)
        else:
            self.gestureUse.setEnabled(True)

    def __gesturePress(self): #是否使用手勢操作
        if self.gestureUse.isChecked():
            self.cameraNum.setEnabled(False)
            self.showCameraUse.setEnabled(True)
            self.__setButtonEnable(False)

            self.isGesThreadRun=True #開啟手勢辨識的執行續
            t = threading.Thread(target=self.__gestureThreadJob)
            t.start()
        elif not self.gestureUse.isChecked():
            self.cameraNum.setEnabled(True)
            self.showCameraUse.setChecked(False)
            self.showCameraUse.setEnabled(False)
            self.__setButtonEnable(True)

            self.isGesThreadRun=False #關閉手勢辨識的執行續   

    def __setButtonEnable(self,isEnable):
        self.nextButton.setEnabled(isEnable)
        self.prevButton.setEnabled(isEnable)
        self.pauseButton.setEnabled(isEnable)
        self.styleButton.setEnabled(isEnable)

    def __nextPress(self):
        print("Next")

    def __prevPress(self):
        print("Prev")
    
    def __pausePress(self):
        print("Pause")
    
    def __stylePress(self):
        print("Style Change")

    def __gestureThreadJob(self):
        while self.isGesThreadRun:
            print("Job")
            time.sleep(3)
        print("Thread End")

if __name__ == '__main__':  
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_GesturePlayer()

    ui.setupUi(MainWindow) 
    MainWindow.show()
    sys.exit(app.exec_())